name: deploy-to-staging

on:
  pull_request:
    branches: [main]
    types: [ready_for_review, synchronize, reopened]

concurrency:
  group: staging-env
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read


jobs:
  deploy-and-e2e:
    if: ${{ github.event.pull_request.draft == false }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_STAGING }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - uses: docker/setup-buildx-action@v3

      - name: Build & push app
        run: |
          docker build -f docker/app/Dockerfile -t ${{ vars.ECR_REPO_APP }}:staging-${GITHUB_SHA} .
          docker tag ${{ vars.ECR_REPO_APP }}:staging-${GITHUB_SHA} ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPO_APP }}:staging-${GITHUB_SHA}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPO_APP }}:staging-${GITHUB_SHA}
